### PR TITLE
fix: change implementation of Annotation#covers according to #317

### LINKED ISSUE #317: Annotations shorter than 5 sec are to long indicated as active
Point-in-time annotations and duration annotations shorter than 5 seconds are displayed as active for 5 seconds (see https://tube.switch.ch/videos/becff00e).

Desired behavior: 
- Point-in-time annotations: Indicated as active for 1 second
- Duration annotations: Active only as long as the actual duration of the annotation

### PR DESCRIPTION
**Pull request by luniki**
Touching Annotation#covers changes:

* Point-in-time annotations are now indicated as active for 1 second
* Duration annotations are now indicated as active only as long as the actual duration of the annotation

Fixes #317

### CODE REVIEW

File: frontend/js/models/annotation.js [hunk 1]
```diff
@@ -242,8 +242,9 @@ define(["underscore",
              */
             covers: function (time, minDuration) {
                 var start = this.get("start");
-                var duration = Math.max(minDuration, this.get("duration") || 0);
-                var end = start + duration;
+                var duration = this.get("duration");
+                var end = duration === 0 ? start + minDuration : start + end;
```
Comment (JulianKniephoff) [inline frontend/js/models/annotation.js]:
```suggestion
                var end = start + (duration || minDuration);
```

? :thinking:

Comment (luniki) [reply frontend/js/models/annotation.js]: Sure.
